# Generated by Django 3.2.4 on 2021-06-07 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='Method')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=200, verbose_name='Address')),
                ('house', models.CharField(max_length=50, verbose_name='Phone number')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of category')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_cost', models.FloatField(default=0, verbose_name='Deposit cost')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of goods')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('barcode', models.CharField(max_length=50, verbose_name='Barcode')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.branch', verbose_name='Owner')),
                ('category_of_goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.category', verbose_name='Category of Goods')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.deposit', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('passport_inn', models.CharField(max_length=20, verbose_name='Passport number')),
                ('phone_num', models.CharField(max_length=50, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='TheCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 12, 12))),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.goods')),
            ],
        ),
        migrations.CreateModel(
            name='RentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('amount', models.IntegerField(verbose_name='Quantity')),
                ('total_price', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.branch')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.goods')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.owner')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.renter')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.accounttype')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentingSystem.owner'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='RentingSystem.owner')),
            ],
        ),
    ]
