# Generated by Django 3.2.4 on 2021-06-07 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='Оплата через:')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50, verbose_name='Район')),
                ('house', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_cost', models.FloatField(default=0, verbose_name='Залог')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('barcode', models.CharField(max_length=50, null=True, verbose_name='Баркод')),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.branch', verbose_name='Арендатор')),
                ('category_of_goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.category', verbose_name='Тип')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.deposit', verbose_name='Залог')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефонный номер')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('passport_inn', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефонный номер')),
            ],
        ),
        migrations.CreateModel(
            name='TheCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0), null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.goods', verbose_name='Цена проката')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Счет оплаты')),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата получения')),
                ('end_date', models.DateTimeField(verbose_name='Дата возврата')),
                ('total_price', models.FloatField()),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.branch')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent2.goods', verbose_name='Товар')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.owner')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.renter')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rent2.owner'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent2.owner')),
            ],
        ),
    ]
